### ISSUE TITLE
Suggestion: Add ability to enter Date+Time for upcoming post

### ISSUE THREAD

**Issue by Mehul** [RickStrahl/MarkdownMonster#186]
Our blog engine provides us the ability to specify a Date and Time that the post will go public. Is there a way to set this (per post) in MM please?

Thanks.

**Comment by RickStrahl** [comment]
Yes you can by providing custom fields in the post metadata:

```yaml
---
title: 'Tip: Create a Visual Studio Menu option to Open a Command Window'
abstract: 'This is the abstract for this blog post... '
keywords: Menu,External Tools, Command Line
categories: ASP.NET, .NET, Visual Studio
weblogName: West Wind Weblog
customFields:
  mt_datetime:
    key: mt_datetime
    value: 5/10/2017
```

(not sure what the custom field value is that you need to set to get the publish time set in your implementation)

On a new post do this:

* Create your post
* Open the publish dialog
* Fill in the post meta data
* Click Save MetaData
* Switch back to the editor
* Go to top
* Add the customFields meta data
* Open the publish dialog again
* Publish

Once you've saved the customFields data with your post it'll be there if you republish.
