### ISSUE TITLE
Code Blocks

### ISSUE THREAD

**Issue by HowardEdidin** [RickStrahl/MarkdownMonster#340]
Is there anyway to show horizontal code blocks?

I hate the way the code looks when it is wrapped.

**Comment by RickStrahl** [comment]
What do you mean by horizontal code blocks?

**Comment by HowardEdidin** [comment]
A Horizontal Scroll Bar



Howard S. Edidin  MCTS, MCP, Author, Trainer, TechNet Wiki Ninja
Senior Integrations and Cloud Architect – Healthcare and Life Sciences

[MVP_Logo_Horizontal_Preferred_Cyan300_CMYK_72ppi]
Microsoft Cosmos DB MVP
Microsoft Virtual Technical Specialist(P-TSP) Cosmos DB, Azure
Microsoft Azure Advisory Group
Azure DocumentDB Wizard

hedidin@edidingroup.com

[btn_viewmy_120x24]<http://www.linkedin.com/in/hedidin>

       [hl7 for biztalk small] <http://www.amazon.com/HL7-for-BizTalk/dp/143026764X/ref=sr_1_1?ie=UTF8&qid=1404753916&sr=8-1&keywords=HL7+for+BizTalk>

O: 224-360-3200
F: 847-816-8995
[Colorlogo-thumbs]<hhttp://www.hl7.org/>HL7 Gold Member

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by RickStrahl** [comment]
What preview theme are you using? The default themes all display a horizontal scrollbar, except perhaps the new KavaDocs ones.

**Comment by RickStrahl** [comment]
Fixed in af96c41b402eefbedc5e8c48900b354ba513bcec

If you want to fix the Github theme yourself:

```css
code {
    font-family: Consolas, monospace;
    color: #333;
    background: #eee;
    white-space: pre;    
}
pre {
    font-family: Consolas, monospace;
    font-weight: normal;    
    font-size: 85%;
    line-height: 1.45;
    margin: 7px 0;
    padding: 0;
    max-width: 98%;
    border: none;
    overflow: auto;    
    border-radius: 3px;
    white-space:  pre;
    word-break: normal;
    word-wrap: normal;
}
pre>code {
    white-space: pre;
    background: #eee !important;
    padding: 1em !important;
}
```
