### ISSUE TITLE
Heading id link glyph

### ISSUE THREAD

**Issue by bitcrazed** [RickStrahl/MarkdownMonster#408]
It's great that MM can auto-generate heading id tags to enable deep-links into specific sections of a post.

It'd be AWESOME if it could also (optionally) append the heading element with a visual glyph hot-linked to the heading so that the reader could right click and copy the link to that heading for pasting elsewhere.

Bonus points if the glyph's visibility is hidden until hovered-over (via inline CSS) :)

**Comment by RickStrahl** [comment]
This isn't really up to the Markdown parser that generates the output - that's the responsibility of your rendering platform. The parser produces raw HTML and it wouldn't make sense to render script and CSS specific logic into the page in this way.

IOW, when you post an .md file to Github, the rendering is handled by GitHub and **they** introduce the link enhancements. Likewise when I post HTML to my blog, some script on my site actually goes in and fixes up the links so you can have those jump links.

Now I could do this for the preview (or you can yourself - the preview is just an HTML page with CSS), but then the preview wouldn't be really representative of anything you'd see on a rendered page and it would even be possible to get that exported into a self-contained page. 

But it wouldn't really help with an export to say Wordpress or another blog since it just receives raw HTML output from the Markdown parser.

**Comment by RickStrahl** [comment]
What might be interesting is allowing adding of CSS and Script tags to posts via a site configuration option. So you could add that sort of logic in script code and custom css that gets shipped with the HTML that is posted. However, I'm not sure if WordPress would even allow that sort of thing - custom HTML and or script/css may very well be stripped out before it goes up.

**Comment by RickStrahl** [comment]
After some more thought about this, this really doesn't belong into the editor. This is something that needs to be handled by the hosting HTML.

If anybody is interested here is some simple jQuery code and CSS that does the selection and injection (you need to change the selector to match your host document):

```js
    function CreateHeaderLinks() {
        var $h3 = $(".content-body>h2,.content-body>h3,.content-body>h4,.content-body>h1");

        $h3.each(function () {            
            var $h3item = $(this);
            $h3item.css("cursor", "pointer");

            var tag = $h3item[0].id; //text().replace(/\s+/g, "");

            var $a = $("<a />")
	            .attr({
	                name: tag,
	                href: "#" + tag
	            })
	            .addClass('link-icon')
	            .addClass('link-hidden')
                .attr('title', 'click this link and set the bookmark url in the address bar.');

            $h3item.prepend($a);

            $h3item
	            .hover(
	                function () {
	                    $a.removeClass("link-hidden");
	                },
	                function () {
	                    $a.addClass("link-hidden");
	                })
	            .click(function () {
	                window.location = $a.prop("href");
	            });
        });
```
here's the relevant CSS that uses the FontAwesome 4 link icon:

```css
.link-icon, link-icon:hover {    
    margin-left: -19px;    
    float: left;
    vertical-align: text-bottom;
    opacity: 0.8;        
    cursor: pointer;
    transition: opacity 0.7s ease-in-out;
    text-decoration: none;    
}
.link-hidden {
    opacity: 0.1;
}
.link-icon::before {
    font-family: FontAwesome;
    font-size: 0.7em;
    content: '\f0c1'; /* fa-link */
    text-decoration: none;
}
```
