### ISSUE TITLE
Add option to prevent image reuploading but keep image source unchanged

### ISSUE THREAD

**Issue by darkthread** [RickStrahl/MarkdownMonster#455]
I used to repost my blog posts over and over to fix typos (I hate myself...) or polish the wording.  By default, MM reupload every image again while post published markdown.  Sometimes it's annoying when there are 20 images embedded in the article that I have to upload several mega bytes of images to fix a character.  

ReplacePostImagesWithOnlineUrls option changes the image source to online image url can prevent duplicated image upload, but the drawback is that the published markdown is a little lousy and hard to preview in offline environment, in addition, the preview browser need to get images from Internet degrade the display performance, too.

Blog editor like Live Writer store the status of uploaded images (XML) in its .wpost file structure.  I think MM can do the same thing to store the MediaObjectInfo in YAML.   Like this:

````YAML
---
title: Article Title
categories: Article Catagory
weblogName: My Blog
postId: 636750117387141574
postDate: 2018-10-13T15:19:58.9009261+08:00
mediaObjects:
  Fig1-t.jpg#kyTFSPTqk7U+ANz06feAEg==:
    uRL: /Posts/files/Fig1-t_636750162581044368.jpg
  Fig2-t.jpg#ONB0d42BVRcWZWaGUOkQrQ==:
    uRL: /Posts/files/Fig2-t_636750162581969729.jpg
---
Blah blah blah blah...
```` 

When MM upload the image, it stores the local file name, content hash, and remote url mapping in YAML.  If the file is unchanged (comparing file name and content hash), MM reads the url from YAML instead of call NewMediaObject() again.  The original img src is not modified, so it won't affect markdown editing and previewing, especially in offline environment.

Embedding MediaObjecInfo in YAML increases the markdown size and makes it ugly, but I think it's OK for those who need this feature and it's optional so normal users won't feel anything wrong.

Here's my implmentation: darkthread@2f832fda3e1fcc9b2af1fec24e456fc668a989e8
