### ISSUE TITLE
antlr code snippets not rendered properly

### ISSUE THREAD

**Issue by gafter** [RickStrahl/MarkdownMonster#578]
A code snippet written like this

```antlr
pattern
    : parenthesized_pattern
    ;
parenthesized_pattern
    : '(' pattern ')'
    ;
```

is rendered in the preview pane like this

![image](https://user-images.githubusercontent.com/3804346/66069465-49112100-e504-11e9-9b40-f046c6c7af68.png)

**Comment by RickStrahl** [comment]
Where is this happening? In the Preview or on your rendered site? If it's the latter it'll be up the hosting Web site to determine what is supported.

In the preview it works for me, although Antlr isn't a supported syntax - it just renders as play text:

![image](https://user-images.githubusercontent.com/1374013/66075258-f2511a80-e4f6-11e9-9022-30ee64865df1.png)

which is what I would expect.

For site rendering it'll depend on what syntax highlighting is running there.

I think the safest bet is probably to just use generic text since Antlr is likely not going to be supported as a language.

````
```text
whatever here
```
````

or perhaps without any language (which will auto-detect which I'm going to guess will pick Yaml).

**Comment by gafter** [comment]
Antlr is a supported language on github.

Please reopen.  It still doesn't work for me:

![image](https://user-images.githubusercontent.com/3804346/66281539-9ed12a80-e870-11e9-8c77-08a558b1bef5.png)

![image](https://user-images.githubusercontent.com/3804346/66281564-bf00e980-e870-11e9-9868-049fc1ea3bd0.png)

**Comment by RickStrahl** [comment]
Ah - ok now I see. It's the theme styling that's the problem.

if you want to fix the Dharkan theme you can paste in the following replacing the css block in `PreviewThemes\Dharkan\Theme.css`.

```css
pre {
  font-family: menlo,consolas,monospace;
  font-weight: normal;
  font-size: 87%;
  line-height: 1.40;
  margin: 7px 0;
  padding: 0;
  border: 1px solid silver;
  border-radius: 5px;
  overflow-x: auto;
  max-width: 98%;
  white-space: pre;
  word-break: normal;
  word-wrap: normal;
  background: #252525;
  color: #eee;
}

pre > code {
  white-space: pre;
  padding: 0.8em !important;
  display: block;
  color: #f5f5f5 !important;
  background: transparent;
  font-weight: normal;
}
```

The template will be updated in the next update.

The problem is that the styling did not set the background color and block spacing for lines properly.

With that change the `antlr` code will display as text, but not as a code snippet in the previewer.

Thanks for keeping with this  - I didn't see this until I could see your exact screen shot including the theme.
