### ISSUE TITLE
Table headers overlapping row in exported PDF

### ISSUE THREAD

**Issue by paulmrozowski** [RickStrahl/MarkdownMonster#616]
This seems to be an issue with the wkhtmltopdf generation, since I see this same issue described [here](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2367)

Basically, if you have a table that extends to multiple pages, it tries to reprint the TH on the new page, but that overlaps the first TD element on that page.

However, I've been playing around with the fixes posted in the thread and they don't seem to help. Any ideas?

**Comment by RickStrahl** [comment]
Played around with this a little and found the fix provided didn't work for me either initially. But I think that's caused by the custom layout features.

So I noticed that my CSS has `display:block` for `table` and that seems to be the problem. Remove that, and it works:

![image](https://user-images.githubusercontent.com/1374013/71854252-abd50400-3081-11ea-8bfc-540b38793779.png)

Try this in `Theme.css` (or create a new theme to copy):

```css
table {
  width: 100%;
  overflow: auto;
  /*  display: table;   <-- remove this or set to 'table'  */
  border-spacing: 0;
  border-collapse: collapse;
  margin: 15px 0;
  border-color: gray;
}
```

Looks like the other 'fixes' aren't needed beyond that. I suspect that those fixes might have been integrated into the Chromium Core, but their triggered by the `table` base selector.

Fixing in my templates.
