### ISSUE TITLE
Make MarkdownMonster installable via WinGet

### ISSUE THREAD

**Issue by yashwanthreddyg** [RickStrahl/MarkdownMonster#708]
WinGet is still in preview, but this would be a great package to have on winget.

**Comment by RickStrahl** [comment]
Looks like it's been already added there:

https://github.com/microsoft/winget-pkgs/tree/master/manifests/WestWind/MarkdownMonster

Not up to date though and I can't update at the moment because I don't have access to WinGet yet.

**Comment by RickStrahl** [comment]
FWIW, here's the latest version manifest:

```yaml
Id: WestWind.MarkdownMonster
Version: 1.24.12
Name: Markdown Monster
Publisher: WestWind
License: © Rick Strahl, West Wind Technologies, 2015-2020
LicenseUrl: https://markdownmonster.west-wind.com/purchase.aspx#License
AppMoniker: markdown-monster
Tags: markdown editor documentation weblog
Description: |
  A powerful, yet easy to use Markdown Editor, Viewer and Weblog Publisher for Windows.
  Create Markdown with a powerful yet low key interface that provides many helpful support features,
  but gets out of your way to keep you productive creating content quickly.
Homepage: https://markdownmonster.west-wind.com/
Installers:
  - Arch: x86
    Url: https://github.com/RickStrahl/MarkdownMonsterReleases/raw/master/v1.24/MarkdownMonsterSetup-1.24.12.exe
    Sha256: DF6E16DBFCF96D919216AD03D70720483862F8155E9D0326B900C595DD696826
    InstallerType: inno
    Switches:
      Silent: /SILENT /VERYSILENT
      SilentWithProgress: /SILENT /VERYSILENT
```

I'll look into getting this updated when releases are made. Not sure if I'll have a good way to automate the update process. 

If somebody wants to help out with getting this auto-scripted that would be helpful. We're already publishing each release to Github with `Install/CreateRelease.ps1` but updating WinGet will require a pull-request so a bit more complex to create automatically.
