### ISSUE TITLE
[Feature Request] View Plain Text

### ISSUE THREAD

**Issue by conradakunga** [RickStrahl/MarkdownMonster#863]
I write my blog in MM using Jekyll natively i.e. I don't' use the built-in Jekyll support.

It works brilliantly.

My challenge comes when I want to use Jekyll's built-in support for posts.

The editor helpfully displays this as a URL.

![image](https://user-images.githubusercontent.com/1281845/136398421-c90a52e7-7519-4c78-83ec-a2a39afc522c.png)

The URL looks like it has underscores, and it is difficult to tell if I have gotten the post URL right, especially at the ends.

Currently, I solve this problem using the Editor Code Syntax menu 

![image](https://user-images.githubusercontent.com/1281845/136399635-7596a859-6a98-4bba-9301-ce126b1f71d3.png)

I wonder if you would consider a context menu item **View As Plain Text** that would shell to notepad (or whatever default specified) and the contents of the editor as plain text

**Comment by RickStrahl** [comment]
Made a change to the default rendering of links. 

```css
span.ace_markup.ace_underline {
  display: inline-block; /* makes it work in IE11 (preview) */
  pointer-events: all;
    text-decoration: none;
}
span.ace_markup.ace_underline:hover {
  color: steelblue;
    text-decoration: underline;
}
```

Basically links are not underlined unless you hover over to indicate that they can be navigated (by Ctrl-Click). This lets you see the link more clearly even on small displays. I suppose this is cleaner and most editor themes show the link already in a different color anyway so it still differentiates.
